apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: x5eb2sfi2-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/x5eb2sfi2-dotnet-basic-gitops